apiVersion: v1
kind: Secret
metadata:
  name: trafficcontrol-secrets
  namespace: dapr-trafficcontrol
type: Opaque
data:
  smtp.user: X3VzZXJuYW1l
  smtp.password: X3Bhc3N3b3Jk
  finecalculator.licensekey: SFg3ODMtSzJMN1YtQ1JKNEEtNVBOMUc=
